[package]
name = "axo"
version = "0.1.0"
edition = "2021"

[dependencies]
broccli = { version = "0.0.22" }
hashish = { version = "0.0.1" }
matchete = { version = "0.0.13" }
log = { version = "0.4.27"}
chrono = "0.4.41"
# inkwell = { path = "inkwell", version = "0.5.0", features = ["default", "llvm18-0"] }

[profile.dev]
debug = true