[package]
name = "axo"
version = "0.1.0"
edition = "2021"

[dependencies]
broccli = { version = "0.0.22" }
axo_hash = { path = "src/axo_hash" }
matchete = { version = "0.0.2" }
# inkwell = { path = "inkwell", version = "0.5.0", features = ["default", "llvm18-0"] }
