[package]
name = "axo"
version = "0.1.0"
edition = "2021"

[features]
default = [
    "internal",
    "formation",
    "initial", "scanner",
    "parser", "resolver",
    #"generator"
]
formation = []
internal = [
    "formation",
    "initial", "scanner",
    "parser", "resolver",
    #"generator",
]
initial = ["formation", "scanner", "parser"]
scanner = ["formation"]
parser = ["formation", "scanner"]
resolver = ["scanner", "parser", "matchete"]
generator = ["resolver", "inkwell"]

[dependencies]
broccli = { version = "0.0.22" }
hashish = { version = "0.0.1" }
log = { version = "0.4.27"}
matchete = { path = "../matchete", optional = true }
walkdir = { version = "2.5.0" }
inkwell = { version = "0.6.0", features = ["llvm18-1-force-static"], optional = true }

[profile.dev]
debug = true