[package]
name = "axo"
version = "0.1.0"
edition = "2021"

[dependencies]
broccli = { version = "0.0.22" }
unic-ucd-common = { path = "src/axo_unicode/common" }
lexical-parse-float = { path = "src/axo_unicode/numeral/lexical-parse-float" }
lexical-parse-integer = { path = "src/axo_unicode/numeral/lexical-parse-integer" }

# inkwell = { path = "inkwell", version = "0.5.0", features = ["default", "llvm18-0"] }
