[package]
name = "axo"
version = "0.1.0"
edition = "2021"

[features]
default = [
    "checker", "formation",
    "text", "initial",
    "scanner", "parser", "resolver",
    "analyzer", #"generator"
]
time = ["chrono"]
checker = []
formation = []
text = []
initial = ["formation", "scanner", "parser"]
scanner = ["formation", "text"]
parser = ["formation", "scanner"]
resolver = ["scanner", "parser", "matchete"]
analyzer = ["scanner", "parser"]
generator = ["analyzer", "inkwell"]

[dependencies]
broccli = { version = "0.0.22" }
hashish = { version = "0.0.1" }
log = { version = "0.4.27"}
matchete = { path = "../matchete", optional = true }
chrono = { version = "0.4.41", optional = true }
walkdir = { version = "2.5.0" }
inkwell = { version = "0.6.0", features = ["llvm18-1-force-static"], optional = true }

[profile.dev]
debug = true